AllCops:
  TargetRubyVersion: 2.5.1

Style/Documentation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
