AllCops:
  TargetRubyVersion: 2.5.1

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'user_engage.gemspec'

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
